#!/bin/sh

# SPYPKG HAS GENERATED THIS FILE!
# If the above comment is modified or removed, 'spypkg' will not deleted this file.
currentdir=$PWD
filename=$(basename "$0")
args="$@"

if [ -f $currentdir/package.json ]; then
  outpath=$(node -pe "JSON.parse(process.argv[1]).spypkg.projectOutPath" "$(cat $currentdir/package.json)")
  adaptorfullpath=$(realpath $currentdir/$outpath/$filename-adaptor.js)

  if [ ! -f "$adaptorfullpath" ]; then
    adaptorfullpath=$(realpath $currentdir/$outpath/adaptor.js)
  fi

  echo "[spypkg] Executing: node " "$adaptorfullpath" "$filename $@"
  node "$adaptorfullpath" "$filename $@"

  ret=$?

  exit $ret
else
  echo "'spypkg' was unable to load 'package.json' in the current directory for '"$filename"' command."
  echo "Remove the following file if not needed: "$0
  exit 1
fi